/*
 * Copyright (c) 2026 David Almeida
 * SPDX-License-Identifier: MIT
 */
package io.github.davidalmeidac.sealedenv.totp;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

import io.github.davidalmeidac.sealedenv.core.Constants;
import io.github.davidalmeidac.sealedenv.core.SealedEnvException;
import io.github.davidalmeidac.sealedenv.core.SealedEnvException.Code;
import io.github.davidalmeidac.sealedenv.crypto.CryptoPrimitives;

import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.util.Base64;
import java.util.UUID;
import java.util.function.Predicate;

/**
 * Unseal token: a compact, signed payload generated by the operator and
 * verified by the application at startup.
 *
 * <p>Format: {@code usl_<base64url(header)>.<base64url(payload)>.<base64url(signature)>}
 *
 * <p>Signed with the file's {@code derived_key} (master_key + salt), so a token
 * cannot be forged from the master key alone — you also need the file's salt.
 *
 * @see <a href="../../../../../../../SPEC.md">.env.sealed v1 specification §9</a>
 */
public final class UnsealToken {

    private static final String TOKEN_PREFIX = "usl_";
    private static final String EXPECTED_TYP = "sealed-env-unseal/v1";
    private static final String EXPECTED_ALG = "HS256";
    private static final String EXPECTED_ISS = "sealed-env-cli";
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Base64.Encoder URL_ENCODER = Base64.getUrlEncoder().withoutPadding();
    private static final Base64.Decoder URL_DECODER = Base64.getUrlDecoder();
    private static final Base64.Decoder STD_DECODER = Base64.getDecoder();
    private static final Base64.Encoder STD_ENCODER = Base64.getEncoder();

    private UnsealToken() {
        throw new AssertionError("no instances");
    }

    public record BuildInput(
            byte[] derivedKey,
            byte[] totpSecret,
            String deployId,
            int ttlSeconds) {
    }

    public record VerifyInput(
            String token,
            byte[] derivedKey,
            String expectedDeployId,
            boolean challengeBindEnabled,
            Predicate<String> isOpsIdSeen,
            Clock clock) {

        public VerifyInput(String token, byte[] derivedKey, String expectedDeployId,
                           boolean challengeBindEnabled) {
            this(token, derivedKey, expectedDeployId, challengeBindEnabled, null,
                    Clock.systemUTC());
        }
    }

    public record VerifyResult(byte[] totpSecret, String opsId) {
    }

    public static String build(BuildInput in) {
        int ttl = Math.min(in.ttlSeconds, Constants.MAX_UNSEAL_TOKEN_AGE_SECONDS);
        if (ttl < 5) {
            throw new SealedEnvException(Code.CONFIG_ERROR,
                    "unseal token TTL too short (min 5s)");
        }
        long now = System.currentTimeMillis() / 1000L;

        ObjectNode header = JSON.createObjectNode();
        header.put("alg", EXPECTED_ALG);
        header.put("typ", EXPECTED_TYP);

        ObjectNode payload = JSON.createObjectNode();
        payload.put("iss", EXPECTED_ISS);
        payload.put("iat", now);
        payload.put("exp", now + ttl);
        payload.put("totp_secret", STD_ENCODER.encodeToString(in.totpSecret));
        if (in.deployId == null) {
            payload.putNull("deploy_id");
        } else {
            payload.put("deploy_id", in.deployId);
        }
        payload.put("ops_id", UUID.randomUUID().toString());

        try {
            String headerB64 = URL_ENCODER.encodeToString(JSON.writeValueAsBytes(header));
            String payloadB64 = URL_ENCODER.encodeToString(JSON.writeValueAsBytes(payload));
            byte[] signingInput = (headerB64 + "." + payloadB64).getBytes(StandardCharsets.UTF_8);
            byte[] sig = CryptoPrimitives.hmacSha256(in.derivedKey, signingInput);
            String sigB64 = URL_ENCODER.encodeToString(sig);
            return TOKEN_PREFIX + headerB64 + "." + payloadB64 + "." + sigB64;
        } catch (Exception e) {
            throw new IllegalStateException("failed to serialize unseal token", e);
        }
    }

    public static VerifyResult verify(VerifyInput in) {
        if (!in.token.startsWith(TOKEN_PREFIX)) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token has wrong prefix");
        }
        String stripped = in.token.substring(TOKEN_PREFIX.length());
        String[] parts = stripped.split("\\.", -1);
        if (parts.length != 3) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token malformed");
        }
        String headerB64 = parts[0];
        String payloadB64 = parts[1];
        String sigB64 = parts[2];

        // Verify signature first — never parse payload of a tampered token.
        byte[] signingInput = (headerB64 + "." + payloadB64).getBytes(StandardCharsets.UTF_8);
        byte[] expectedSig = CryptoPrimitives.hmacSha256(in.derivedKey, signingInput);
        byte[] providedSig;
        try {
            providedSig = URL_DECODER.decode(sigB64);
        } catch (IllegalArgumentException e) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token signature unreadable");
        }
        if (!CryptoPrimitives.constantTimeEqual(expectedSig, providedSig)) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token signature invalid");
        }

        JsonNode header;
        JsonNode payload;
        try {
            header = JSON.readTree(URL_DECODER.decode(headerB64));
            payload = JSON.readTree(URL_DECODER.decode(payloadB64));
        } catch (Exception e) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token payload malformed");
        }

        if (!EXPECTED_ALG.equals(asText(header, "alg"))
                || !EXPECTED_TYP.equals(asText(header, "typ"))) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token has unexpected header");
        }

        long now = in.clock.instant().getEpochSecond();
        long exp = asLong(payload, "exp", -1L);
        long iat = asLong(payload, "iat", -1L);
        if (exp <= now) {
            throw new SealedEnvException(Code.TOKEN_EXPIRED, "unseal token expired");
        }
        if (iat > now + 5) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token issued in the future");
        }
        if (exp - iat > Constants.MAX_UNSEAL_TOKEN_AGE_SECONDS) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token TTL too long");
        }

        if (in.challengeBindEnabled) {
            JsonNode deployIdNode = payload.get("deploy_id");
            String deployId = (deployIdNode == null || deployIdNode.isNull())
                    ? null : deployIdNode.asText();
            if (deployId == null) {
                throw new SealedEnvException(Code.DEPLOY_MISMATCH,
                        "unseal token missing deploy_id");
            }
            if (!deployId.equals(in.expectedDeployId)) {
                throw new SealedEnvException(Code.DEPLOY_MISMATCH,
                        "unseal token bound to a different deploy");
            }
        }

        String opsId = asText(payload, "ops_id");
        if (in.isOpsIdSeen != null && in.isOpsIdSeen.test(opsId)) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token already used (replay)");
        }

        byte[] totpSecret;
        try {
            totpSecret = STD_DECODER.decode(asText(payload, "totp_secret"));
        } catch (Exception e) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token totp_secret unreadable");
        }
        if (totpSecret.length < 16) {
            throw new SealedEnvException(Code.TOKEN_INVALID, "unseal token totp_secret too short");
        }

        return new VerifyResult(totpSecret, opsId);
    }

    private static String asText(JsonNode node, String field) {
        JsonNode v = node.get(field);
        return v == null ? null : v.asText();
    }

    private static long asLong(JsonNode node, String field, long fallback) {
        JsonNode v = node.get(field);
        return v == null ? fallback : v.asLong(fallback);
    }
}
