/*
 * Copyright (c) 2026 David Almeida
 * SPDX-License-Identifier: MIT
 */
package io.github.davidalmeidac.sealedenv;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.github.davidalmeidac.sealedenv.core.KdfAlgorithm;
import io.github.davidalmeidac.sealedenv.core.KdfParams;
import io.github.davidalmeidac.sealedenv.core.SealedFile;
import io.github.davidalmeidac.sealedenv.format.SealedFileParser;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HexFormat;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * SEC-002 cross-stack regression: Java must successfully decrypt a sealed file
 * that was written by Node with N=131072 (OWASP 2024 scrypt floor).
 *
 * <p>Test vector: {@code test-vectors/v1/enterprise-scrypt-N131072.json}
 * (generated by {@code node/scripts/gen-scrypt-n131072-vector.mjs}).
 */
class ScryptN131072DecryptTest {

    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Path VECTORS_DIR = Path.of("..", "..", "test-vectors", "v1");

    static boolean vectorsAvailable() {
        return Files.isDirectory(VECTORS_DIR) &&
               Files.exists(VECTORS_DIR.resolve("enterprise-scrypt-N131072.json"));
    }

    @Test
    @EnabledIf("vectorsAvailable")
    @DisplayName("Java decrypts a Node-sealed file with scrypt N=131072 (SEC-002)")
    void javaDecryptsN131072Vector() throws Exception {
        Path p = VECTORS_DIR.resolve("enterprise-scrypt-N131072.json");
        JsonNode v = JSON.readTree(Files.readString(p, StandardCharsets.UTF_8));

        SealedFile file = SealedFileParser.parse(v.get("serialized").asText());

        // Assert the parser correctly identified N=131072
        assertThat(file.kdf()).isEqualTo(KdfAlgorithm.SCRYPT);
        assertThat(file.kdfParams()).isInstanceOf(KdfParams.Scrypt.class);
        KdfParams.Scrypt scrypt = (KdfParams.Scrypt) file.kdfParams();
        assertThat(scrypt.N()).isEqualTo(131072);
        assertThat(scrypt.r()).isEqualTo(8);
        assertThat(scrypt.p()).isEqualTo(1);

        // Decrypt and assert plaintext matches
        SealedEnv.UnsealOptions u = new SealedEnv.UnsealOptions();
        u.file = file;
        u.masterKey = HexFormat.of().parseHex(v.get("masterKeyHex").asText());

        byte[] plaintext = SealedEnv.unseal(u);
        assertThat(new String(plaintext, StandardCharsets.UTF_8))
                .isEqualTo(v.get("plaintext").asText());
    }
}
